version: '3.9'

services:
  db:
    container_name: project_management_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changethispassword!
      POSTGRES_DB: projectmanagementapp
    ports:
      - "5455:5432"
    restart: unless-stopped
